### ISSUE TITLE
installation failed on nimble dependency in 0.4

### ISSUE THREAD

**Issue by jrousemd** [michael-franke/aida-package#4]
having installation issues in RStudio. R version is 4.0.3.
looks to this novice like it has to do with removal of nimble in 0.4.

error message as below:

> remotes::install_github('michael-franke/aida-package')
Downloading GitHub repo michael-franke/aida-package@HEAD
✓  checking for file ‘/private/var/folders/__/n18d49_n3gd4qy2tvblzprnm0000gp/T/Rtmp71Tlau/remotes2ea178b606bb/michael-franke-aida-package-db75c37/DESCRIPTION’ ...
─  preparing ‘aida’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘aida_0.4.tar.gz’
   
* installing *source* package ‘aida’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘nimble’
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package ‘aida’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/aida’
Error: Failed to install 'aida' from GitHub:
  (converted from warning) installation of package ‘/var/folders/__/n18d49_n3gd4qy2tvblzprnm0000gp/T//Rtmp71Tlau/file2ea176741ce6/aida_0.4.tar.gz’ had non-zero exit status

**Comment by MarauderPixie** [comment]
Thanks for reporting! There was indeed an oversight in removing `nimble` (which lead to the package still being listed in `NAMESPACE`. Installation should work now without calling for `nimble` for good.

**Comment by jrousemd** [comment]
contacted author, issue fixed, installation works so easily now that a middle aged M.D. can do it!
